spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres.railway.internal}:${DATABASE_PORT:5432}/${DATABASE_NAME:railway}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:sPzpNuaLURBWtIaLpoGeURUkIjZWgVcQ}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect